import 'package:flutter/material.dart';

class MyBasicModel {
  final String title, subtitle;
  final IconData? icon;
  final VoidCallback? onTap;
  final List<dynamic> list;
  MyBasicModel({
    required this.title,
    this.icon,
    this.onTap,
    required this.subtitle,
    required this.list,
  });
}

List<MyBasicModel> basicList = [
  MyBasicModel(
      title: "Profession",
      icon: Icons.shopping_bag_outlined,
      onTap: () {},
      list: [
        "Doctor",
        "IT Professional",
        "Entrepreneur",
        "Unemployed",
        "Manager",
        "Teacher",
        "Scientist",
        "Lawyer",
        "Author",
        "Film Maker",
      ],
      subtitle: "Doctor"),
  MyBasicModel(
    title: "Education",
    icon: Icons.sticky_note_2_outlined,
    onTap: () {},
    subtitle: "High School",
    list: [
      "Education",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "Height",
    icon: Icons.person_outline_sharp,
    onTap: () {},
    subtitle: "175 cm",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "Personality",
    icon: Icons.height,
    onTap: () {},
    subtitle: "ENFG",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "Drinking habits",
    icon: Icons.emoji_emotions_outlined,
    onTap: () {},
    subtitle: "Socially",
    list: [
      "Socially",
      "Never",
      "Frequency",
    ],
  ),
  MyBasicModel(
    title: "Smoking habits",
    icon: Icons.local_drink_outlined,
    onTap: () {},
    subtitle: "Socially",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "Religion",
    icon: Icons.smoking_rooms_sharp,
    onTap: () {},
    subtitle: "Spirtual",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "Looking for",
    icon: Icons.new_releases_outlined,
    onTap: () {},
    subtitle: "Relationship",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "Zodiac sign",
    icon: Icons.favorite_border_sharp,
    onTap: () {},
    subtitle: "Cancer",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
  MyBasicModel(
    title: "I Identify as",
    icon: Icons.recycling_outlined,
    onTap: () {},
    subtitle: "Diabetes",
    list: [
      "Doctor",
      "IT Professional",
      "Entrepreneur",
      "Unemployed",
      "Manager",
      "Teacher",
      "Scientist",
      "Lawyer",
      "Author",
      "Film Maker",
    ],
  ),
];
//
// List<MyBasicModel> professionList = [
//   MyBasicModel(
//     title: "Doctor",
//     subtitle: '',
//   ),
//   MyBasicModel(title: "IT Professional", subtitle: ''),
//   MyBasicModel(title: "Entrepreneur", subtitle: ''),
//   MyBasicModel(title: "Unemployed", subtitle: ''),
//   MyBasicModel(title: "Manager", subtitle: ''),
//   MyBasicModel(title: "Teacher", subtitle: ''),
//   MyBasicModel(title: "Scientist", subtitle: ''),
//   MyBasicModel(title: "Lawyer", subtitle: ''),
//   MyBasicModel(title: "Auther", subtitle: ''),
//   MyBasicModel(title: "Film Maker", subtitle: ''),
// ];
